input_dim: 375614
output_dim: 6
objective: 'multiclass'
boosting: 'gbdt'
learning_rate: 0.05
num_leaves: 31
device: 'gpu'
max_depth: -1
min_data_in_leaf: 20
feature_fraction: 0.9
bagging_fraction: 0.8
bagging_freq: 5
verbose: 0