# https://github.com/aimhubio/aim

aim:
  _target_: aim.pytorch_lightning.AimLogger
  repo: ${work_dir}/logs/.aim # full path to parent directory of Aim repo - the .aim directory (optional)
  experiment: null # a name of the experiment (optional)
  train_metric_prefix: train_ # the prefix of metrics names collected in the training loop. By default train_
  test_metric_prefix: val_ # the prefix of metrics names collected in the test loop. By default test_
  val_metric_prefix: test_ # the prefix of metrics names collected in the validation loop. By default val_
  flush_frequency: 128 # the frequency per step to flush intermediate aggregated values of metrics to disk. By default per 128 step.
  system_tracking_interval: 10 # system resource usage tracking interval in seconds. By default 10 seconds.
