# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "mean_absolute_error"
optimized_mean: "cv_mean" # "cv_mean_val_test"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 200

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 50
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    params:
      pytorch_tabular_autoint.optimizer_lr: tag(log, interval(0.00001, 1))
      pytorch_tabular_autoint.attn_embed_dim: choice(16, 32)
      pytorch_tabular_autoint.num_heads: choice(1, 2, 4, 8)
      pytorch_tabular_autoint.num_attn_blocks: choice(1, 2, 3)
      pytorch_tabular_autoint.attn_dropouts: choice(0.0, 0.1)
      pytorch_tabular_autoint.has_residuals: choice(True, False)
      pytorch_tabular_autoint.embedding_dim: choice(8, 16, 32)
      pytorch_tabular_autoint.embedding_dropout: choice(0.0, 0.1)
      pytorch_tabular_autoint.deep_layers: choice(False, True)
