# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "mean_absolute_error"
optimized_mean: "cv_mean" # "cv_mean_val_test"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 200

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 35
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    params:
      widedeep_saint.optimizer_lr: tag(log, interval(0.0001, 0.05)) # tag(log, interval(0.00001, 1))
      widedeep_saint.optimizer_weight_decay: tag(log, interval(0.000001, 0.15)) # tag(log, interval(0.00000001, 0.1))
      widedeep_saint.embed_dim: choice(4, 6, 8) # choice(2, 4)
      widedeep_saint.n_heads: choice(2, 3) # choice(1, 2)
      widedeep_saint.n_blocks: choice(1) # choice(1, 2)
      widedeep_saint.attn_dropout: choice(0.0, 0.025, 0.05) # choice(0.05, 0.1, 0.2)
      widedeep_saint.ff_dropout: choice(0.075, 0.1) # choice(0.05, 0.1, 0.2)
      widedeep_saint.mlp_hidden_dims: choice([100, 50, 1]) # choice([200, 100, 1], [100, 50, 1], [200, 100, 50, 1])
      widedeep_saint.mlp_dropout: choice(0.0, 0.02, 0.05) # choice(0.05, 0.1, 0.15)

