# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: agena/inference       # Global parameters of experiment
  - datamodule: agena/tabular         # Information about dataset
  - trainer: null                     # Run configuration for DNN models
  - callbacks: null                   # Callbacks for DNN models
  - logger: none                      # Loggers for DNN models
  - hydra: default.yaml               # Output paths for logs

  - model: agena/elastic_net             # Model
  - hparams_search: null              # Model-specific hyperparameters

  # Enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
