# @package _global_

sa_model: catboost

# specify here defaults
defaults:
  - trainer: null
  - model: null
  - datamodule: null
  - callbacks: null
  - logger: null

  - experiment: tabnetpl
  - hparams_search: null

  - hydra: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog


