# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: covid19/regression/status_day         # Global parameters of experiment
  - datamodule: covid19/regression/status_day             # Information about dataset
  - trainer: gpu                          # Run configuration for DNN models
  - callbacks: default # none                    # Callbacks for DNN models
  - logger: none                          # Loggers for DNN models
  - hydra: default                        # Output paths for logs

  - model: covid19/regression/status_day/lightgbm                 # Model
  - hparams_search: covid19/regression/status_day/lightgbm        # Model-specific hyperparameters

  # Enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
