# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: covid19_status/trn_val_tst         # Global parameters of experiment
  - datamodule: covid19_status/tabular             # Information about dataset
  - trainer: gpu                          # Run configuration for DNN models
  - callbacks: default                    # Callbacks for DNN models
  - logger: none                          # Loggers for DNN models
  - hydra: default.yaml                   # Output paths for logs

  - model: covid19_status/widedeep_ft_transformer                 # Model
  - hparams_search: covid19_status/widedeep_ft_transformer        # Model-specific hyperparameters

  # Enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
