# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: covid19/survival/status         # Global parameters of experiment
  - datamodule: covid19/survival/status             # Information about dataset
  - trainer: gpu                          # Run configuration for DNN models
  - callbacks: none                    # Callbacks for DNN models
  - logger: none                          # Loggers for DNN models
  - hydra: default.yaml                   # Output paths for logs

  - model: covid19/survival/status/rsf                 # Model
  - hparams_search: covid19/survival/status/rsf        # Model-specific hyperparameters

  # Enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
