# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: immuno/classification/esrd_trn_val_tst         # Global parameters of experiment
  - datamodule: immuno/classification/esrd                     # Information about dataset
  - trainer: gpu                                  # Run configuration for DNN models
  - callbacks: default # none                     # Callbacks for DNN models
  - logger: none                                  # Loggers for DNN models
  - hydra: default                                # Output paths for logs

  - model: immuno/classification/esrd/lightgbm              # Model
  - hparams_search: immuno/classification/esrd/lightgbm      # Model-specific hyperparameters

  # Enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
