# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: dnam/classification/parkinson_trn_val_tst         # Global parameters of experiment
  - datamodule: dnam/classification/parkinson                     # Information about dataset
  - trainer: gpu                                  # Run configuration for DNN models
  - callbacks: default # none                     # Callbacks for DNN models
  - logger: none                                  # Loggers for DNN models
  - hydra: default                                # Output paths for logs

  - model: dnam/classification/parkinson/widedeep_tab_net                # Model
  - hparams_search: dnam/classification/parkinson/widedeep_tab_net       # Model-specific hyperparameters

  # Enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
