_target_: src.datamodules.dnam.betas_pheno.BetasPhenoDataModule

path: "E:/YandexDisk/Work/pydnameth/datasets/GPL13534/meta/BrainDiseases/variance(0.005)"
outcome: "Status"
batch_size: 30
train_val_test_split: [0.9, 0.1, 0.1]
num_workers: 0
pin_memory: False
seed: 42
weighted_sampler: False
