_target_: src.datamodules.dnam.betas_pheno.BetasPhenoDataModule

path: "E:/YandexDisk/Work/pydnameth/datasets/meta/d11b5f9b6efd089db42a3d5e6b375430"
cpgs_fn: "E:/YandexDisk/Work/pydnameth/datasets/meta/d11b5f9b6efd089db42a3d5e6b375430/cpgs/375614.xlsx"
statuses_fn: "E:/YandexDisk/Work/pydnameth/datasets/meta/d11b5f9b6efd089db42a3d5e6b375430/statuses/6.xlsx"
outcome: "Status"
batch_size: 30
train_val_test_split: [0.7, 0.15, 0.15]
num_workers: 0
pin_memory: False
seed: 42
weighted_sampler: False